/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v2ANRXHxRXn
 */
import { ResizablePanel, ResizableHandle, ResizablePanelGroup } from "@/(components)//ui/resizable"
import { Button } from "@/(components)//ui/button"
import ReactPlayer from 'react-player'


export function ChatComponent() {
  return (
    <div key="1" className="flex flex-col h-screen w-full lg:flex-row">
      <div className="border-b lg:border-r w-full lg:w-[1040px] flex flex-col">
        <div className="flex h-14 items-center px-4 border-b lg:border-b-0">
          <div className="text-xl font-bold text-gray-900 dark:text-gray-50">Video Chat</div>
        </div>
        <div className="flex-1 flex items-center justify-center">
          <ResizablePanelGroup className="max-w-3xl w-full p-2 rounded-lg border" direction="horizontal">
            <ResizablePanel defaultSize={200}>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <div className="flex items-center gap-2">
                    <Button size="sm" variant="outline" className="flex-1">Mute</Button>
                    <Button size="sm" variant="outline" className="flex-1">Stop Video</Button>
                  </div>
                  <Button size="sm" variant="outline" className="flex-1">Share Screen</Button>
                </div>
                <div className="flex-1 flex items-center justify-center">
                  <ReactPlayer
                    url="https://www.youtube.com/watch?v=ysz5S6PUM-U"
                    width="100%"
                    height="100%"
                  />
                </div>
              </div>
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={0} />
          </ResizablePanelGroup>
        </div>
      </div>
      <div className="border-t lg:border-t-0 lg:border-l w-full lg:w-full flex flex-col">
        <div className="flex-1 flex flex-col">
          <div className="h-14 flex items-center px-4 border-b">
            <form className="flex items-center w-full">
              <input
                className="flex-1 h-10 px-4 rounded-l-lg border-r-0 focus:outline-none"
                placeholder="Enter video URL"
                type="text"
              />
              <button type="submit" className="h-10 px-4 bg-gray-900 text-white rounded-r-lg border-l-0">Go</button>
            </form>
          </div>
          <div className="grid gap-2">
            <div className="rounded-xl border w-full aspect-video">
              <span className="w-full aspect-video rounded-md bg-muted" />
            </div>
          </div>
        </div>
        <div className="h-20 flex items-center px-4">
          <div className="grid gap-2">
            <div className="text-sm font-medium">What's the best way to get started with a new framework?</div>
            <div className="text-xs text-gray-500 dark:text-gray-400">Posted by Sarah 2 minutes ago</div>
          </div>
        </div>
      </div>
    </div>
  )
}

